-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, E.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES E
JOIN HR_GRADE G ON G.EMP_NO = E.EMP_NO
WHERE G.YEAR = 2022
GROUP BY
    EMP_NO
ORDER BY SCORE DESC
LIMIT 1;