SELECT FI.ID,
       FNI.FISH_NAME,
       FI.LENGTH
FROM FISH_INFO FI
JOIN (
    SELECT FISH_TYPE,
           MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) SUB
ON FI.FISH_TYPE = SUB.FISH_TYPE
AND FI.LENGTH = SUB.MAX_LENGTH
JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
ORDER BY FI.ID ASC;