SELECT c.CAR_ID,
       MAX(CASE
           WHEN c.END_DATE >= '2022-10-16' AND c.START_DATE <= '2022-10-16'   
           THEN "대여중"
           ELSE "대여 가능"
       END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as c 
GROUP BY c.CAR_ID
ORDER BY 1 DESC