SELECT
    ID,
    CASE
        WHEN SIZE_INTERVAL = 1 THEN 'LOW'
        WHEN SIZE_INTERVAL = 2 THEN 'MEDIUM'
        WHEN SIZE_INTERVAL = 3 THEN 'HIGH'
        ELSE 'CRITICAL'
    END AS COLONY_NAME
FROM (
    SELECT
        ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY ASC) AS SIZE_INTERVAL
    FROM ECOLI_DATA
) SIZE_SEP_TABLE
ORDER BY ID ASC
