SELECT A.CATEGORY AS CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK AS A JOIN BOOK_SALES AS B
ON A.BOOK_ID = B.BOOK_ID AND B.SALES_DATE >= '2022-01-01' AND B.SALES_DATE < '2022-02-01'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;