SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A 
JOIN FISH_NAME_INFO AS B 
    ON A.FISH_TYPE = B.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) M
    ON A.FISH_TYPE = M.FISH_TYPE AND A.LENGTH = M.MAX_LENGTH
ORDER BY ID ASC;