SELECT a.FLAVOR
FROM(SELECT f.FLAVOR , (f.TOTAL_ORDER + j.TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF as f
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER, SHIPMENT_ID
    FROM JULY
    GROUP BY FLAVOR
) as j
ON f.SHIPMENT_ID = j.SHIPMENT_ID
ORDER BY TOTAL_ORDER DESC ) as a
LIMIT 3
